# Generated by Django 2.2.6 on 2019-10-05 01:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=220, null=True)),
                ('symbol_image', models.ImageField(upload_to='symbols')),
                ('context_image', models.ImageField(upload_to='manuscripts')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expansion', models.CharField(blank=True, max_length=220, null=True)),
                ('transcription', models.CharField(blank=True, max_length=220, null=True)),
                ('text', models.CharField(blank=True, max_length=220, null=True)),
                ('date', models.CharField(blank=True, max_length=220, null=True)),
                ('place', models.CharField(blank=True, max_length=220, null=True)),
                ('scribe', models.CharField(blank=True, max_length=220, null=True)),
                ('manuscript', models.CharField(blank=True, max_length=220, null=True)),
                ('images', models.ManyToManyField(blank=True, to='greek_app.Image', verbose_name='Images(s)')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_type', to='greek_app.Type')),
            ],
        ),
    ]
