# Generated by Django 3.0.7 on 2020-06-26 21:20

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='symbols/')),
                ('image_height', models.PositiveIntegerField(blank=True, default='400', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default=None, editable=False, null=True)),
                ('expansion', models.CharField(blank=True, max_length=220, null=True)),
                ('base_expansion', models.CharField(blank=True, max_length=220, null=True)),
                ('transcription', models.CharField(blank=True, max_length=220, null=True)),
                ('author', models.CharField(blank=True, max_length=220, null=True)),
                ('text_title', models.CharField(blank=True, max_length=220, null=True)),
                ('archive', models.CharField(blank=True, max_length=220, null=True)),
                ('city', models.CharField(blank=True, max_length=220, null=True)),
                ('date', models.CharField(blank=True, max_length=220, null=True)),
                ('place', models.CharField(blank=True, max_length=220, null=True)),
                ('scribe', models.CharField(blank=True, max_length=220, null=True)),
                ('folia', models.CharField(blank=True, max_length=220, null=True)),
                ('manuscript_shelfmark', models.CharField(blank=True, max_length=220, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('sketch', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('symbol_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_type', to='greek_app.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.ManyToManyField(blank=True, to='greek_app.Symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
