# Generated by Django 2.2.6 on 2019-10-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='symbol_image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='image',
            name='context_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
