# Generated by Django 2.2.6 on 2019-10-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0002_auto_20191005_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='greek_app/static/symbols'),
        ),
    ]
