# Generated by Django 2.2.6 on 2019-10-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0003_auto_20191005_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='images',
        ),
        migrations.AddField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='greek_app/static/symbols'),
        ),
    ]
