# Generated by Django 2.2.6 on 2019-10-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0004_auto_20191005_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='symbols/'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='symbols/'),
        ),
    ]
