# Generated by Django 2.2.6 on 2019-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0005_auto_20191005_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/symbols/'),
        ),
    ]
