# Generated by Django 2.2.6 on 2019-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0009_auto_20191008_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to='symbols/', width_field=True),
        ),
    ]
