# Generated by Django 2.2.6 on 2019-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0010_auto_20191008_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='symbols/'),
        ),
    ]
