# Generated by Django 2.2.6 on 2019-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0011_auto_20191008_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
