# Generated by Django 2.2.6 on 2019-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0012_auto_20191008_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='base_expansion',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
