# Generated by Django 2.2.7 on 2020-06-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_app', '0013_symbol_base_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
